export enum category {
  GIAO_VIEN_MAM_NON = 'Giáo viên mầm non',
  GIAO_VIEN_TIEU_HOC = 'Giáo viên tiểu học',
  GIAO_VIEN_NGU_VAN = 'Giáo viên ngữ văn',
  GIAO_VIEN_TOAN = 'Giáo viên toán',
  GIAO_VIEN_TIENG_ANH = 'Giáo viên tiếng Anh',
  GIAO_VIEN_GDCD = 'Giáo viên giáo dục công dân',
  GIAO_VIEN_LICH_SU = 'Giáo viên lịch sử',
  GIAO_VIEN_DIA_LI = 'Giáo viên địa lí',
  GIAO_VIEN_KHOA_HOC_TN = 'Giáo viên khoa học tự nhiên',
  GIAO_VIEN_CONG_NGHE = 'Giáo viên công nghệ',
  GIAO_VIEN_TIN_HOC = 'Giáo viên tin học',
  GIAO_VIEN_THE_CHAT = 'Giáo viên giáo dục thể chất',
  GIAO_VIEN_NGHE_THUAT = 'Giáo viên nghệ thuật (âm nhạc, mĩ thuật)',
  GIAO_VIEN_HOAT_DONG_TRAI_NGHIEM = 'Giáo viên hoạt động trải nghiệm, hướng nghiệp',
  GIAO_VIEN_VAT_LY = 'Giáo viên vật lý',
  GIAO_VIEN_HOA_HOC = 'Giáo viên hoá học',
  GIAO_VIEN_GDIA_PHUONG = 'Giáo viên giáo dục địa phương',
  GIAO_VIEN_TIENG_PHAP = 'Giáo viên tiếng Pháp',
  GIAO_VIEN_TIENH_DUC = 'Giáo viên tiếng Đức',
  GIAO_VIEN_TIENG_NGA = 'Giáo viên tiếng Nga',
  GIAO_VIEN_TIENG_NHAT = 'Giáo viên tiếng Nhật',
  GIAO_VIEN_TIENG_HAN = 'Giáo viên tiếng Hàn',
  GIAO_VIEN_TIENG_TRUNG = 'Giáo viên tiếng Trung',
  GIAO_VIEN_TIENG_TBN = 'Giáo viên tiếng Tây Ban Nha',
  GIAO_VIEN_STEM = 'Giáo viên StEM/StEAM',
  TRO_GIANG = 'Trợ giảng',
  TRO_GIANG_TIENG_ANH = 'Trợ giảng tiếng Anh',
  TRO_GIANG_TOAN = 'Trợ giảng toán',
}

export const CategoryList = Object.values(category)
