export enum ISO {
  DATE_TIME = 'YYYY-MM-DD HH:mm:ss',
  DATE = 'YYYY-MM-DD',
  TIME = 'HH:mm:ss',
  DATE_TIME_WITH_SLASH = 'YYYY/MM/DD HH:mm:ss',
  DATE_WITH_SLASH = 'YYYY/MM/DD',
  DATE_TIME_MINUS_SLASH = 'YYYY/MM/DD HH:mm',
  DATE_TIME_MINUS = 'YYYY-MM-DD HH:mm',
  DATE_TIME_SECOND = 'YYYY-MM-DD HH:ss',
  DATE_STRING = 'YYYYMMDD',
}
