export enum location {
  TuyenQuang = 'Tuyên Quang',
  CaoBang = 'Cao Bằng',
  LaiChau = 'Lai Châu',
  LaoCai = 'Lào Cai',
  ThaiNguyen = 'Thái Nguyên',
  DienBien = 'Điện Biên',
  LangSon = 'Lạng Sơn',
  SonLa = 'Sơn La',
  PhuTho = 'Phú Thọ',
  BacNinh = 'Bắc Ninh',
  QuangNinh = 'Quảng Ninh',
  HaNoi = 'TP. Hà Nội',
  HaiPhong = 'TP. Hải Phòng', // 13
  HungYen = 'Hưng Yên',
  NinhBinh = 'Ninh Bình',
  ThanhHoa = 'Thanh Hóa',
  NgheAn = 'Nghệ An',
  HaTinh = 'Hà Tĩnh',
  QuangTri = 'Quảng Trị',
  Hue = 'TP. Huế',
  DaNang = 'TP. Đà Nẵng',
  QuangNgai = 'Quảng Ngãi',
  GiaLai = 'Gia Lai',
  DakLak = 'Đắk Lắk',
  KhanhHoa = 'Khánh Hoà',
  LamDong = 'Lâm Đồng',
  DongNai = 'Đồng Nai',
  TayNinh = 'Tây Ninh',
  HoChiMinh = 'TP. Hồ Chí Minh', //29
  DongThap = 'Đồng Tháp',
  AnGiang = 'An Giang',
  VinhLong = 'Vĩnh Long',
  CanTho = 'TP. Cần Thơ',
  CaMau = 'Cà Mau',
}

export const LocationList = Object.values(location)
