export enum MasterDataItem {
  Category = 'category',
  Location = 'location',
  JobBenefits = 'jobBenefits',
  ExperienceLevel = 'experienceLevel',
  TypeOfEmployment = 'typeOfEmployment',
}

export enum Category {
  giaovienmamnon = 1,
  giaovientieuhoc = 2,
  giaoviennguvan = 3,
  giaovientoan = 4,
  giaovientienganh = 5,
  giaoviengdcd = 6,
  giaovienlichsu = 7,
  giaoviendiali = 8,
  giaovienkhoahoctn = 9,
  giaoviencongnghe = 10,
  giaovientinhoc = 11,
  giaovienthechat = 12,
  giaoviennghethuat = 13,
  giaovienhoatdongtrainghiem = 14,
  giaovienvatly = 15,
  giaovienhoahoc = 16,
  giaoviengdiaphuong = 17,
  giaovientiengphap = 18,
  giaovientienhduc = 19,
  giaovientiengnga = 20,
  giaovientiengnhat = 21,
  giaovientienghan = 22,
  giaovientiengtrung = 23,
  giaovientiengtbn = 24,
  giaovienstem = 25,
  trogiang = 26,
  trogiangtienhanh = 27,
  trogiangtoan = 28,
}

export enum Location {
  tuyenquang = 1,
  caobang = 2,
  laichau = 3,
  laocai = 4,
  thainguyen = 5,
  dienbien = 6,
  langson = 7,
  sonla = 8,
  phutho = 9,
  bacninh = 10,
  quangninh = 11,
  hanoi = 12,
  haiphong = 13,
  hungyen = 14,
  ninhbinh = 15,
  thanhhoa = 16,
  nghean = 17,
  hatinh = 18,
  quangtri = 19,
  hue = 20,
  danang = 21,
  quangngai = 22,
  gialai = 23,
  daklak = 24,
  khanhhoa = 25,
  lamdong = 26,
  dongnai = 27,
  tayninh = 28,
  hochiminh = 29,
  dongthap = 30,
  angiang = 31,
  vinhlong = 32,
  cantho = 33,
  camau = 34,
}
